-- No-op: enum types and enum columns are already created by 20260523170000_sms_voting.
-- This migration previously duplicated CREATE TYPE and TEXT→enum ALTER statements for an
-- earlier draft of 20260523170000_sms_voting that used TEXT columns. Kept in history so
-- applied migration records remain valid; safe to replay on shadow and production DBs.
