import type { GlobalTemplateSeed } from "@/lib/judging/seed-templates/judging-template-types";
import {
  aacaDiscretionaryOther,
  aacaFullSubcategory,
  aacaLevelsViolationsSubcategory,
} from "@/lib/judging/seed-templates/judging-template-types";

export const AACA_AUTOMOBILE_TEMPLATE: GlobalTemplateSeed = {
  slug: "aaca",
  name: "AACA Automobile Judging Starter",
  scoringGroup: "AACA",
  vehicleType: "Auto",
  description:
    "Starter scorecard based on provided AACA Automobile Judging Form sample (400 pts). Event organizers should review and customize. Not an official AACA rulebook.",
  methodology: "DEDUCTION",
  totalPoints: 400,
  sortOrder: 3,
  categories: [
    {
      name: "Exterior",
      maxSectionPoints: 100,
      subcategories: [
        aacaFullSubcategory("Antenna", 2),
        aacaFullSubcategory("Beading / Welting", 3),
        aacaLevelsViolationsSubcategory("Body: Door", 10, "Per door", 5),
        aacaLevelsViolationsSubcategory("Fender", 20, "Per fender", 5),
        aacaFullSubcategory("Hood", 5),
        aacaFullSubcategory("Roof / Top hard", 5),
        aacaFullSubcategory("Trim / Striping / Moldings / Decal", 10),
        aacaFullSubcategory("Trunk", 5),
        aacaFullSubcategory("Color", 10),
        aacaFullSubcategory("Non-Authentic", 40),
        aacaLevelsViolationsSubcategory("Cowl Vent / Seal", 6, "Per component", 3),
        aacaFullSubcategory("Dirt - Excessive", 3),
        aacaLevelsViolationsSubcategory("Door Handle", 8, "Per handle", 2),
        aacaFullSubcategory("Grille", 5),
        aacaFullSubcategory("Hood Ornament", 3),
        aacaLevelsViolationsSubcategory("Head Light", 6, "Per lamp", 3),
        aacaLevelsViolationsSubcategory("Driving / Fog Light", 6, "Per lamp", 3),
        aacaLevelsViolationsSubcategory("Side / Parking Light", 6, "Per lamp", 3),
        aacaLevelsViolationsSubcategory("Tail / Lens", 6, "Per lens", 3),
        aacaFullSubcategory("Material, non-authentic body component", 40),
        aacaLevelsViolationsSubcategory("Mirror", 6, "Per mirror", 3),
        aacaLevelsViolationsSubcategory("Running Boards", 10, "Per board", 5),
        aacaFullSubcategory("Spoiler", 5),
        aacaLevelsViolationsSubcategory("Window Frames exterior", 12, "Per frame", 3),
        aacaLevelsViolationsSubcategory("Windshield / Frame / Gasket", 6, "Per unit", 3),
        aacaLevelsViolationsSubcategory("Windshield Wiper", 6, "Per wiper", 3),
        aacaDiscretionaryOther(),
      ],
    },
    {
      name: "Interior",
      maxSectionPoints: 100,
      subcategories: [
        aacaFullSubcategory("A/C under dash if incorrect", 10),
        aacaFullSubcategory("Carpet / Floor Material / Mats", 5),
        aacaFullSubcategory("Clock", 3),
        aacaFullSubcategory("Console", 3),
        aacaFullSubcategory("Dashboard / Instrument Panel", 3),
        aacaFullSubcategory("Dirt - Excessive", 3),
        aacaLevelsViolationsSubcategory("Door Handle", 8, "Per handle", 2),
        aacaLevelsViolationsSubcategory("Door Panel / Seals / Jambs", 12, "Per door", 3),
        aacaLevelsViolationsSubcategory("Door Sills", 6, "Per sill", 3),
        aacaLevelsViolationsSubcategory("Glass", 12, "Per pane", 3),
        aacaFullSubcategory("Headliner / Sail Panel", 5),
        aacaLevelsViolationsSubcategory("Instruments / Gauges", 12, "Per item", 3),
        aacaLevelsViolationsSubcategory("Interior Light", 6, "Per light", 3),
        aacaFullSubcategory("Mirror", 3),
        aacaLevelsViolationsSubcategory("Pedal / Lever", 8, "Per item", 2),
        aacaFullSubcategory("Radio / Sound System", 10),
        aacaLevelsViolationsSubcategory("Seat Belts", 8, "Per belt", 2),
        aacaFullSubcategory("Upholstery if incorrect", 10),
        aacaLevelsViolationsSubcategory("Seat Cushion / Back", 20, "Per seat", 5),
        aacaFullSubcategory("Steering Wheel", 3),
        aacaFullSubcategory("Soft Top Condition", 10),
        aacaFullSubcategory("Soft Top Down / Missing", 10),
        aacaLevelsViolationsSubcategory("Soft Top Fasteners", 10, "Per fastener", 1),
        aacaFullSubcategory("Soft Top Material if incorrect", 10),
        aacaFullSubcategory("Convertible Back Window", 5),
        aacaFullSubcategory("Side Curtains Missing", 10),
        aacaLevelsViolationsSubcategory("Window Crank", 8, "Per crank", 2),
        aacaDiscretionaryOther(),
      ],
    },
    {
      name: "Chassis",
      maxSectionPoints: 100,
      subcategories: [
        aacaLevelsViolationsSubcategory("Front Axles", 10, "Per axle", 5),
        aacaFullSubcategory("Rear Axle", 5),
        aacaFullSubcategory("Brakes", 3),
        aacaFullSubcategory("Hydraulic brakes if incorrect", 10),
        aacaLevelsViolationsSubcategory("Brake Lines / Cables / Rods", 8, "Per line", 2),
        aacaLevelsViolationsSubcategory("Body Bolts", 10, "Per bolt", 1),
        aacaLevelsViolationsSubcategory("Front Bumper", 10, "Per bumper", 5),
        aacaLevelsViolationsSubcategory("Rear Bumper", 10, "Per bumper", 5),
        aacaLevelsViolationsSubcategory("Bumper Guards", 12, "Per guard", 3),
        aacaFullSubcategory("Differential / Columbia Rear End", 3),
        aacaFullSubcategory("Dirt - Excessive", 3),
        aacaFullSubcategory("Drive Shaft", 3),
        aacaFullSubcategory("Exhaust System", 5),
        aacaFullSubcategory("Frame", 5),
        aacaLevelsViolationsSubcategory("Fuel / Vacuum Lines", 10, "Per line", 1),
        aacaFullSubcategory("Gas Tank", 3),
        aacaLevelsViolationsSubcategory("Hub Caps / Wheel Covers", 12, "Per cover", 3),
        aacaLevelsViolationsSubcategory("Lock Rings", 8, "Per ring", 2),
        aacaLevelsViolationsSubcategory("Lug Nuts if visible", 10, "Per nut", 1),
        aacaLevelsViolationsSubcategory("Rim / Wheel including spare", 10, "Per wheel", 2),
        aacaLevelsViolationsSubcategory("Tires including spares", 10, "Per tire", 2),
        aacaFullSubcategory("Under Carriage", 5),
        aacaLevelsViolationsSubcategory("Valve Stem", 10, "Per stem", 1),
        aacaLevelsViolationsSubcategory("Valve Cap / Cover", 10, "Per cap", 1),
        aacaDiscretionaryOther(),
      ],
    },
    {
      name: "Engine",
      maxSectionPoints: 100,
      subcategories: [
        aacaLevelsViolationsSubcategory("Air Cleaner / Carburetor", 10, "Per unit", 5),
        aacaFullSubcategory("Air Conditioning Compressor", 3),
        aacaLevelsViolationsSubcategory("Condenser / Evaporator", 6, "Per unit", 3),
        aacaFullSubcategory("Non-Authentic", 10),
        aacaFullSubcategory("Battery", 5),
        aacaLevelsViolationsSubcategory("Belts", 10, "Per belt", 2),
        aacaFullSubcategory("Block / Crankcase", 15),
        aacaFullSubcategory("Coil", 3),
        aacaFullSubcategory("Dirt Excessive", 3),
        aacaFullSubcategory("Distributor / Magneto", 5),
        aacaFullSubcategory("Emissions after 1967", 5),
        aacaFullSubcategory("Expansion Tank / Coolant Reservoir", 3),
        aacaLevelsViolationsSubcategory("Fan Blade / Clutch / Shroud", 9, "Per item", 3),
        aacaLevelsViolationsSubcategory("Filters", 10, "Per filter", 2),
        aacaFullSubcategory("Firewall", 3),
        aacaFullSubcategory("Fuel Supply / Lines", 5),
        aacaFullSubcategory("Electric fuel supply if added post-war", 10),
        aacaFullSubcategory("Generator / Alternator", 5),
        aacaLevelsViolationsSubcategory("Heads / Valve Covers", 10, "Per side", 5),
        aacaLevelsViolationsSubcategory("Hood Hinge / Catch / Insulation", 10, "Per item", 5),
        aacaLevelsViolationsSubcategory("Horns", 6, "Per horn", 3),
        aacaLevelsViolationsSubcategory("Hose", 10, "Per hose", 2),
        aacaLevelsViolationsSubcategory("Clamps", 10, "Per clamp", 1),
        aacaLevelsViolationsSubcategory("Manifold Exhaust / Intake", 10, "Per manifold", 5),
        aacaFullSubcategory("Manifold Non-Authentic", 10),
        aacaLevelsViolationsSubcategory("Radiator Cap / Core / Tank", 15, "Per item", 5),
        aacaLevelsViolationsSubcategory("Spark Plugs", 10, "Per plug", 1),
        aacaLevelsViolationsSubcategory("Spark Plug Wires", 10, "Per wire", 1),
        aacaFullSubcategory("Starter", 5),
        aacaLevelsViolationsSubcategory("Tape / Tubing / Terminals", 10, "Per item", 1),
        aacaFullSubcategory("Voltage Regulator", 3),
        aacaFullSubcategory("Water Pump", 5),
        aacaLevelsViolationsSubcategory("Wiring", 10, "Per run", 1),
        aacaDiscretionaryOther(),
      ],
    },
  ],
};
